helper.tcl: Fix TCL redirection error (use >& and not &>)
In TCL, the syntax for redirection of stdout and stderr is '>& fileName',
not '&> fileName'. While this seems to present no issue on some systems
(for unclear reasons, maybe some locally installed tcl is used instead
of the Vivado internally provided ; problematic system had no local tcl),
it leads to strangely failing builds in correlation with git, see below.

Problematic are intermediate errors when calling "git status -s", with
misleading error messages like
  Failed (warning: could not open directory 'ip/example/pl/&>/dev/': No such file or directory)
  ERROR: Failed GIT build commit. Continue packaging ...
and consecutive errors
  Failed to exeucte packaging of example_ip_core
  child process exited abnormally
which result in a failed build process.

Fix this by correcting the redirection, i.e. use '>&' at all places.

Signed-off-by: Andreas Pretzsch <apr@nyxe.de>